"""renamed fields to generic storage key

Revision ID: 4f2521e8bf17
Revises: 3686be00a031
Create Date: 2025-04-17 15:16:06.850784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f2521e8bf17'
down_revision: Union[str, None] = '3686be00a031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_interview_sessions', sa.Column('job_description_storage_key', sa.String(), nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('resume_storage_key', sa.String(), nullable=False))
    op.add_column('mock_interview_sessions', sa.Column('questions_mapping_storage_key', sa.String(), nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('interview_log_storage_key', sa.String(), nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('ai_feedback_storage_key', sa.String(), nullable=True))
    op.drop_column('mock_interview_sessions', 'interview_log_s3_url')
    op.drop_column('mock_interview_sessions', 'job_description_s3_url')
    op.drop_column('mock_interview_sessions', 'resume_s3_url')
    op.drop_column('mock_interview_sessions', 'previous_questions_s3_url')
    op.drop_column('mock_interview_sessions', 'ai_feedback_s3_url')
    op.add_column('resumes', sa.Column('resume_storage_key', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('resume_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('resumes', 'resume_data')
    op.drop_column('resumes', 's3_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('s3_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('resume_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'resume_metadata')
    op.drop_column('resumes', 'resume_storage_key')
    op.add_column('mock_interview_sessions', sa.Column('ai_feedback_s3_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('previous_questions_s3_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('resume_s3_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mock_interview_sessions', sa.Column('job_description_s3_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('interview_log_s3_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mock_interview_sessions', 'ai_feedback_storage_key')
    op.drop_column('mock_interview_sessions', 'interview_log_storage_key')
    op.drop_column('mock_interview_sessions', 'questions_mapping_storage_key')
    op.drop_column('mock_interview_sessions', 'resume_storage_key')
    op.drop_column('mock_interview_sessions', 'job_description_storage_key')
    # ### end Alembic commands ###
