"""Move JSON fields to S3 URLs in MockInterviewSession

Revision ID: 5709ad826a91
Revises: dcd43669e6df
Create Date: 2025-04-09 14:58:06.945035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5709ad826a91'
down_revision: Union[str, None] = 'dcd43669e6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_interview_sessions', sa.Column('job_description_s3_url', sa.String(), nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('previous_questions_s3_url', sa.String(), nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('interview_log_s3_url', sa.String(), nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('ai_feedback_s3_url', sa.String(), nullable=True))
    op.drop_column('mock_interview_sessions', 'job_description')
    op.drop_column('mock_interview_sessions', 'previous_questions')
    op.drop_column('mock_interview_sessions', 'ai_feedback')
    op.drop_column('mock_interview_sessions', 'interview_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_interview_sessions', sa.Column('interview_log', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('ai_feedback', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('previous_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mock_interview_sessions', sa.Column('job_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('mock_interview_sessions', 'ai_feedback_s3_url')
    op.drop_column('mock_interview_sessions', 'interview_log_s3_url')
    op.drop_column('mock_interview_sessions', 'previous_questions_s3_url')
    op.drop_column('mock_interview_sessions', 'job_description_s3_url')
    # ### end Alembic commands ###
